### ISSUE TITLE
LICENSE missing in sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [calmjs/calmjs.parse#27]
Hi! I'm packaging calmjs.parse for Arch Linux.
Similar to the [issue with calmjs.types](https://github.com/calmjs/calmjs.types/issues/1), calmjs.parse is missing the LICENSE in the pypi sdist tarball.

**Comment by metatoaster** [comment]
Thanks for also the report on calmjs.types (and the other packaging issues you have reported across the calmjs project), I will be getting this sorted over the weekend.
