### ISSUE TITLE
Fix importing the ABCs

### ISSUE THREAD

**Issue by KristobalJunta** [calmjs/calmjs.parse#31]
Running the current version of calmjs.parse on python 3.7 a warning is raised about deprecation of ABCs import:

```
.venv/lib/python3.7/site-packages/calmjs/parse/io.py:7
  .venv/lib/python3.7/site-packages/calmjs/parse/io.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Iterable
```

**Comment by metatoaster** [comment]
This was an artefact of supporting (the now unsupported) Python 2.7, as that was the original import location.  As the release of Python 3.9 is not imminent, a fix for this will be created nonetheless but won't be released immediately.

**Comment by metatoaster** [comment]
In any case, thank you for your report and your original pull request. Even if the pull request was not accepted this time, please don't feel discourage and naturally please don't hesitate to bring your contributions should the need arise in another time.

**Comment by KristobalJunta** [comment]
No problems here and thank you for the great library.

Wouldn't have pushed, if I actually noticed your response earlier :)
