### ISSUE TITLE
WARNING message

### ISSUE THREAD

**Issue by prrvchr** [calmjs/calmjs.parse#43]
Hi,

I use calmjs in a LibreOffice extension. The calmjs package comes with the extension in a directory [pythonpath](https://github.com/prrvchr/OAuth2OOo/tree/master/source/OAuth2OOo/service/pythonpath) that LibreOffice adds to the python path.

Since I use calmj I have a message when importing the module:

> WARNING: Token 'BLOCK_COMMENT' defined, but not used
> WARNING: Token 'LINE_COMMENT' defined, but not used
> WARNING: Token 'LINE_TERMINATOR' defined, but not used
> WARNING: There are 3 unused tokens

Maybe there is a way to stop getting these warning messages?

Thanks.

**Comment by metatoaster** [comment]
Duplicate #42

**Comment by metatoaster** [comment]
Moreover, I cloned your project and couldn't replicate your exact issue, even when using `PYTHONPATH` as you indicated:

```
$ PYTHONPATH=/tmp/Oauth2OOo/source/OAuth2OOo/service/pythonpath/ python -c "from calmjs.parse import es5;print(repr(es5('var one = 1;')))"
<ES5Program @1:1 ?children=[
  <VarStatement @1:1 ?children=[
    <VarDecl @1:5 identifier=<Identifier ...>, initializer=<Number ...>>
  ]>
]>
```

**Comment by metatoaster** [comment]
Another way to verify whether or not the tab modules are available (which would silent the warning as they only come up during the generation of the lex/yacc tables) is to see if the expected generated modules are available - see the following:

```console
$ PYTHONPATH=/tmp/OAuth2OOo/source/OAuth2OOo/service/pythonpath/ python -c \
>     "from calmjs.parse.utils import generate_tab_names;print(generate_tab_names('calmjs.parse.parsers.es5'))"
('calmjs.parse.parsers.lextab_es5_py3_ply3_11', 'calmjs.parse.parsers.yacctab_es5_py3_ply3_11')
$ # Verify that the above import locations work
$ PYTHONPATH=/tmp/OAuth2OOo/source/OAuth2OOo/service/pythonpath/ python -c \
>     "import calmjs.parse.parsers.lextab_es5_py3_ply3_11, calmjs.parse.parsers.yacctab_es5_py3_ply3_11"
$ # Now remove the existing modules
$ /bin/rm /tmp/OAuth2OOo/source/OAuth2OOo/service/pythonpath/calmjs/parse/parsers/yacctab_es5_py3_ply3_11.py
$ /bin/rm /tmp/OAuth2OOo/source/OAuth2OOo/service/pythonpath/calmjs/parse/parsers/lextab_es5_py3_ply3_11.py
$ # This would now replicate the error you saw:
$ PYTHONPATH=/tmp/OAuth2OOo/source/OAuth2OOo/service/pythonpath/ python -c \
>     "from calmjs.parse import es5; es5('')"
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
```

**Comment by prrvchr** [comment]
Thank you for all these explanations, I see things more clearly now.

The warnings come from the fact that I launch an optimization in one of the ini files of the extension:
```
# FIXME: We need to force the creation of tab files using the utf8 codec to workaround issues with
# FIXME: the ply package, for systems like Windows that do not have utf8 configured as the default codec.
from calmjs.parse.parsers.optimize import reoptimize_all
reoptimize_all(True)
```
I would have to test if this has not already been done before launching the optimization, in order to get rid of its warnings. Besides, how can I easily find out?

On the other hand I manage to obtain the version of calmjs installed with the help of the pkg_resources package.
However when I obtain the version I also have a warning:
```
WARNING: Package <calmjs.parse> does not provide 'Requires-Python' metadata: open an issue if possible on the package site
WARNING: Package <calmjs.types> does not provide 'Requires-Python' metadata: open an issue if possible on the package site
```

**Comment by metatoaster** [comment]
The optimization only needs to run once, if the optimization modules are already present and the underlying lexer/parser hasn't been changed it doesn't need to be run. Since you vendored everything in a monorepo that optimization step should only ever be run if you pull in new versions (and even then, just use the source release found on PyPI which would contain this generated module).

As for your second issue it's not a critical packaging issue (`Requires-Python` is a new requirement to squelch the warning, wasn't the case at the time when the package was authored). In any case the next release for those packages will come with the relevant version metadata.

**Comment by prrvchr** [comment]
Ok and thank you for all your explanations...
